In [1]:
#numpy-numeric python
#array
#difference between array n list

a=[2,3,4,5]
print(type(a))

<class 'list'>


In [2]:
import numpy as np         #more efficient for numeric operation
b=np.array([2,3,4,5])
print(type(b))

<class 'numpy.ndarray'>


In [3]:
b/2

array([1. , 1.5, 2. , 2.5])

In [4]:
a_op=[]
for i in range(2,6,1):
  a_op.append(i/2)
a_op

[1.0, 1.5, 2.0, 2.5]

In [ ]:
# 1 dimension vector
# 2 dimension matrix
# 3 or more tensor

In [5]:
b=np.array([2,3,4,5])
print (b.ndim)

1


In [6]:
b=np.array([[2,3,4,5],
           [6,7,8,9]])
print (b.ndim)
print(b)

2
[[2 3 4 5]
 [6 7 8 9]]


In [7]:
x= np.array([2,3])
y= np.array([4,5])
print(x+y)
print(y-x)

[6 8]
[2 2]


In [8]:
np.add(x,y)

array([6, 8])

In [9]:
np.sum([3,4])

7

In [10]:
m=np.array([0,20,40,60,80,100])
print(np.max(m))
print(np.min(m))
print(np.mean(m))
print(np.median(m))

100
0
50.0
50.0


In [11]:
import numpy as np
a=np.array([2,5])
b=np.array([6,8])
np.sqrt(np.sum(np.square(np.subtract(a,b))))

5.0

In [12]:
np.linalg.norm(a-b)

5.0

In [13]:
#euler
a=np.array([],dtype=int)
b=np.array([],dtype=int)
for i in range(2):
  a=np.append(a,int(input()))
for i in range(2):
  b=np.append(b,int(input()))
np.sqrt(np.sum(np.square(np.subtract(a,b))))

7
14
3
4


10.770329614269007

In [14]:
#normalisation
c=np.array([2,5,7,9])
cmin=np.min(c)
cmin


2

In [15]:
cmax=np.max(c)
cmax

9

In [16]:
cscaled=c-cmin/cmax-cmin
cscaled

array([-0.22222222,  2.77777778,  4.77777778,  6.77777778])

In [17]:
#dot product of two matrices
c=np.array([[2,4,6],[3,6,9]])
d=np.array([[3,2],[1,2],[5,10]])
np.dot(c,d)

array([[ 40,  72],
       [ 60, 108]])

In [18]:
#mean squarre error
import numpy as np
y_pred=np.array([110,220,330])
y_real=np.array([100,200,300])
error=np.subtract(y_pred,y_real)
error

array([10, 20, 30])

In [19]:
sqerror=np.square(error)
sqerror

array([100, 400, 900])

In [20]:
mean_sq_error=np.mean(sqerror)
mean_sq_error

466.6666666666667

In [21]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_real)

466.6666666666667